
[book]
authors = ["Dustin Firebaugh"]
src = "src"
title = "banana book"

[output.html]
default-theme = "simple"
site-url = "/bbook"
github-repo-icon = "fa-github"
github-repo-url = "https://github.com/dfirebaugh/bbook"
